# Generated by Django 4.2.5 on 2023-09-26 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chatbox', '0002_rename_chatbot_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Chatb',
        ),
    ]
